name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write # コンテンツノートの書き込み権限を有効にする
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: |
          go build -ldflags "-X main.version=${{ env.VERSION }}" \
            -o "${{ runner.temp }}/example" go/example/main.go
      - run: |
          gh release create "${{ env.VERSION }}"  --title "${{ env.VERSION }}" --generate-notes
          gh release upload "${{ env.VERSION }}" "${{ runner.temp }}/example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
